name: iql
channels:
- defaults
- conda-forge
dependencies:
- python=3.8
- setuptools==65.5.0
- "wheel<0.40.0"
- pip
- patchelf
- pip:
    - numpy
    - scipy
    - pandas
    - tqdm
    - gym[mujoco]==0.18.0
    - torch>=1.7.0
    - git+https://github.com/Farama-Foundation/d4rl@f2a05c0d66722499bf8031b094d9af3aea7c372b#egg=d4rl
